---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend
  namespace: apps
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: lattice-alb2
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /live
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/set-identifier: "1"
    external-dns.alpha.kubernetes.io/aws-weight: "100"      
spec:
  ingressClassName: awslb-store
  rules:
    - host: frontend-eks.lattice.sarathy.io
      http:
        paths:
          - path: /popular
            pathType: Prefix
            backend:
              service:
                name: frontend-auth-svc
                port:
                  number: 80       
          - path: /summary
            pathType: Prefix
            backend:
              service:
                name: frontend-auth-svc
                port:
                  number: 80   
                                                             
                  
